"use client";

import { useState, useEffect } from "react";
import { FileBox, FileJson, Clock, Target, CalendarDays, ExternalLink, Activity, ScanLine, X } from "lucide-react";
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from "@/components/ui/card";
import { ScrollArea } from "@/components/ui/scroll-area";
import { Badge } from "@/components/ui/badge";
import { Dialog, DialogContent, DialogDescription, DialogHeader, DialogTitle } from "@/components/ui/dialog";
import { Button } from "@/components/ui/button";

export default function ArtifactsClient({
    initialArtifacts
}: {
    initialArtifacts: any[]
}) {
    const [artifacts, setArtifacts] = useState(initialArtifacts);
    const [selectedText, setSelectedText] = useState<string | null>(null);

    // Polling loop for real-time updates
    useEffect(() => {
        const intervalId = setInterval(async () => {
            try {
                const res = await fetch("/api/artifacts");
                if (res.ok) {
                    const data = await res.json();
                    if (data.artifacts) {
                        setArtifacts(data.artifacts);
                    }
                }
            } catch (err) {
                console.error("Artifacts polling error", err);
            }
        }, 5000); // 5 seconds

        return () => clearInterval(intervalId);
    }, []);

    const formatBytes = (bytes: number) => {
        if (bytes === 0) return '0 B';
        const k = 1024;
        const sizes = ['B', 'KB', 'MB', 'GB'];
        const i = Math.floor(Math.log(bytes) / Math.log(k));
        return parseFloat((bytes / Math.pow(k, i)).toFixed(2)) + ' ' + sizes[i];
    };

    return (
        <div className="flex-1 overflow-auto bg-zinc-950/30 p-8 h-full">
            <div className="max-w-7xl mx-auto space-y-6">

                {/* Header */}
                <div className="flex flex-col md:flex-row md:items-center justify-between gap-4">
                    <div>
                        <h1 className="text-3xl font-semibold tracking-tight text-zinc-100 flex items-center gap-3">
                            <FileBox className="w-8 h-8 text-indigo-400" />
                            Workforce Artifacts
                        </h1>
                        <p className="text-zinc-400 mt-2">
                            A centralized repository of deliverables, reports, and data outputs generated by OpenClaw agents.
                        </p>
                    </div>
                </div>

                {/* Artifacts Table */}
                <Card className="bg-zinc-900/50 border-zinc-800/80 backdrop-blur-sm overflow-hidden">
                    <CardHeader className="border-b border-zinc-800/80 bg-zinc-900/40 px-6 py-5 flex flex-row items-center justify-between">
                        <div>
                            <CardTitle className="text-lg font-medium text-zinc-100 flex items-center gap-2">
                                <FileJson className="w-5 h-5 text-indigo-400" />
                                Generated Files ({artifacts.length})
                            </CardTitle>
                            <CardDescription className="text-zinc-400 mt-1">Live polling for new deliverables.</CardDescription>
                        </div>
                        <div className="flex items-center gap-2">
                            <Activity className="w-4 h-4 text-emerald-400 animate-pulse" />
                            <span className="text-xs text-emerald-500/80 font-medium">Auto-Sync Active</span>
                        </div>
                    </CardHeader>
                    <CardContent className="p-0">
                        <ScrollArea className="max-h-[600px] w-full">
                            <div className="min-w-max">
                                {artifacts.length === 0 ? (
                                    <div className="p-8 text-center flex flex-col items-center justify-center text-zinc-500 h-64">
                                        <ScanLine className="w-10 h-10 mb-4 text-zinc-700 animate-pulse" />
                                        <p>No artifacts found.</p>
                                        <p className="text-sm mt-2">Outputs generated by Agents will appear here automatically.</p>
                                    </div>
                                ) : (
                                    <table className="w-full text-sm text-left">
                                        <thead className="text-xs text-zinc-400 uppercase bg-zinc-900/80 border-b border-zinc-800/50 sticky top-0 z-10 backdrop-blur-md">
                                            <tr>
                                                <th className="px-6 py-4 font-medium tracking-wider w-[20%]">Artifact Kind</th>
                                                <th className="px-6 py-4 font-medium tracking-wider w-[35%]">Project Context</th>
                                                <th className="px-6 py-4 font-medium tracking-wider w-[10%]">Size</th>
                                                <th className="px-6 py-4 font-medium tracking-wider w-[20%]">Date Created</th>
                                                <th className="px-6 py-4 font-medium tracking-wider w-[15%] text-right">Actions</th>
                                            </tr>
                                        </thead>
                                        <tbody className="divide-y divide-zinc-800/50 text-zinc-300">
                                            {artifacts.map((artifact) => (
                                                <tr key={artifact.id} className="hover:bg-zinc-800/30 transition-colors group">
                                                    <td className="px-6 py-4 font-medium flex items-center gap-3">
                                                        <FileBox className="w-5 h-5 text-indigo-500/70" />
                                                        <div className="flex flex-col">
                                                            <span className="text-zinc-200 capitalize">{artifact.kind || "Data"}</span>
                                                            <span className="text-xs text-zinc-500 font-mono mt-0.5">{artifact.contentType || "text/plain"}</span>
                                                        </div>
                                                    </td>
                                                    <td className="px-6 py-4">
                                                        <div className="flex flex-col">
                                                            <span className="text-zinc-300 font-medium">{artifact.projectGoal || "Orphaned Task"}</span>
                                                            <span className="text-xs text-zinc-500 mt-1 flex items-center gap-1">
                                                                <Target className="w-3 h-3" />
                                                                {artifact.taskType || "unknown task"}
                                                            </span>
                                                        </div>
                                                    </td>
                                                    <td className="px-6 py-4 text-zinc-400 font-mono text-xs">
                                                        {formatBytes(artifact.sizeBytes || 0)}
                                                    </td>
                                                    <td className="px-6 py-4 whitespace-nowrap text-zinc-400 flex items-center gap-2">
                                                        <CalendarDays className="w-4 h-4 text-zinc-500" />
                                                        {new Date(artifact.createdAt).toLocaleString(undefined, {
                                                            month: 'short', day: 'numeric',
                                                            hour: '2-digit', minute: '2-digit'
                                                        })}
                                                    </td>
                                                    <td className="px-6 py-4 text-right">
                                                        {artifact.storageUrl ? (
                                                            <Button variant="outline" size="sm" asChild className="opacity-0 group-hover:opacity-100 transition-opacity border-indigo-500/30 hover:bg-indigo-500/10 hover:text-indigo-300 text-indigo-400 bg-transparent h-8">
                                                                <a href={artifact.storageUrl} target="_blank" rel="noopener noreferrer">
                                                                    Open Link <ExternalLink className="w-3 h-3 ml-2" />
                                                                </a>
                                                            </Button>
                                                        ) : artifact.contentText ? (
                                                            <Button onClick={() => setSelectedText(artifact.contentText)} variant="outline" size="sm" className="opacity-0 group-hover:opacity-100 transition-opacity border-emerald-500/30 hover:bg-emerald-500/10 hover:text-emerald-300 text-emerald-400 bg-transparent h-8">
                                                                View Content
                                                            </Button>
                                                        ) : (
                                                            <span className="text-xs text-zinc-600 italic">No Payload</span>
                                                        )}
                                                    </td>
                                                </tr>
                                            ))}
                                        </tbody>
                                    </table>
                                )}
                            </div>
                        </ScrollArea>
                    </CardContent>
                </Card>

            </div>

            {/* Content View Modal */}
            <Dialog open={!!selectedText} onOpenChange={(open) => !open && setSelectedText(null)}>
                <DialogContent className="sm:max-w-[700px] bg-zinc-950 border-zinc-800 text-zinc-200 shadow-2xl p-0 gap-0">
                    <DialogHeader className="px-6 py-4 border-b border-zinc-800/80 bg-zinc-900/50 flex flex-row items-center justify-between">
                        <div>
                            <DialogTitle className="text-lg font-semibold tracking-tight">Artifact Payload</DialogTitle>
                            <DialogDescription className="text-zinc-400 mt-1">Raw text payload extracted from the database.</DialogDescription>
                        </div>
                    </DialogHeader>

                    <div className="p-6 bg-zinc-950 max-h-[60vh] overflow-y-auto">
                        <pre className="text-sm font-mono text-zinc-300 whitespace-pre-wrap bg-zinc-900/50 p-4 border border-zinc-800/50 rounded-lg">
                            {selectedText}
                        </pre>
                    </div>

                </DialogContent>
            </Dialog>

        </div>
    );
}
